import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  title: {
    default: "Next.js tutorial- Codevolution",  //acts as a fallback for any child routes that don't specify their own title
    template: "%s | Codevolution", //when u want to add constant prefixes/suffixes to your title; property applies to child route
    // absolute: "", //sometimes when want to break free from template pattern set by parent segments
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
